"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-07 08:09:58.430784
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('reply_to', sa.String(length=320), nullable=True),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_security', sa.Enum('ssl', 'starttls', 'none', name='security', native_enum=False, length=16), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('rate_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_accounts_name'))
    )
    op.create_table('mailing_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mailing_lists')),
    sa.UniqueConstraint('name', name=op.f('uq_mailing_lists_name'))
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_templates_name'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'paused', 'completed', 'cancelled', name='campaignstatus', native_enum=False, length=16), nullable=False),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_campaigns_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_campaigns_template_id_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_status_scheduled_at', ['status', 'scheduled_at'], unique=False)

    op.create_table('campaign_lists',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_lists_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['mailing_lists.id'], name=op.f('fk_campaign_lists_list_id_mailing_lists'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('campaign_id', 'list_id', name=op.f('pk_campaign_lists'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'unsubscribed', 'bounced', 'complained', name='contactstatus', native_enum=False, length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_campaign_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['status_campaign_id'], ['campaigns.id'], name=op.f('fk_contacts_status_campaign_id_campaigns'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts')),
    sa.UniqueConstraint('email', name=op.f('uq_contacts_email'))
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', 'skipped', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('smtp_code', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=998), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_deliveries_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_deliveries_contact_id_contacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('campaign_id', 'contact_id', name=op.f('uq_deliveries_campaign_contact'))
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_deliveries_campaign_status_next', ['campaign_id', 'status', 'next_attempt_at'], unique=False)
        batch_op.create_index('ix_deliveries_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_deliveries_sent_at', ['sent_at'], unique=False)

    op.create_table('list_members',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_list_members_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['mailing_lists.id'], name=op.f('fk_list_members_list_id_mailing_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'contact_id', name=op.f('pk_list_members'))
    )
    with op.batch_alter_table('list_members', schema=None) as batch_op:
        batch_op.create_index('ix_list_members_contact_id', ['contact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_members', schema=None) as batch_op:
        batch_op.drop_index('ix_list_members_contact_id')

    op.drop_table('list_members')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_deliveries_sent_at')
        batch_op.drop_index('ix_deliveries_message_id')
        batch_op.drop_index('ix_deliveries_campaign_status_next')

    op.drop_table('deliveries')
    op.drop_table('contacts')
    op.drop_table('campaign_lists')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_status_scheduled_at')

    op.drop_table('campaigns')
    op.drop_table('templates')
    op.drop_table('mailing_lists')
    op.drop_table('accounts')
    # ### end Alembic commands ###
